// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeNumber    float32                `protobuf:"fixed32,1,opt,name=node_number,json=nodeNumber,proto3" json:"node_number,omitempty"`
	Temperature_C float32                `protobuf:"fixed32,2,opt,name=temperature_C,json=temperatureC,proto3" json:"temperature_C,omitempty"`
	Humidity      float32                `protobuf:"fixed32,3,opt,name=humidity,proto3" json:"humidity,omitempty"`
	HeatIndex     float32                `protobuf:"fixed32,4,opt,name=heat_index,json=heatIndex,proto3" json:"heat_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataPoint) Reset() {
	*x = DataPoint{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataPoint) ProtoMessage() {}

func (x *DataPoint) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataPoint.ProtoReflect.Descriptor instead.
func (*DataPoint) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *DataPoint) GetNodeNumber() float32 {
	if x != nil {
		return x.NodeNumber
	}
	return 0
}

func (x *DataPoint) GetTemperature_C() float32 {
	if x != nil {
		return x.Temperature_C
	}
	return 0
}

func (x *DataPoint) GetHumidity() float32 {
	if x != nil {
		return x.Humidity
	}
	return 0
}

func (x *DataPoint) GetHeatIndex() float32 {
	if x != nil {
		return x.HeatIndex
	}
	return 0
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\x12\x06helper\x1a\x1bgoogle/protobuf/empty.proto\"\x8c\x01\n" +
	"\tDataPoint\x12\x1f\n" +
	"\vnode_number\x18\x01 \x01(\x02R\n" +
	"nodeNumber\x12#\n" +
	"\rtemperature_C\x18\x02 \x01(\x02R\ftemperatureC\x12\x1a\n" +
	"\bhumidity\x18\x03 \x01(\x02R\bhumidity\x12\x1d\n" +
	"\n" +
	"heat_index\x18\x04 \x01(\x02R\theatIndex2H\n" +
	"\tCollector\x12;\n" +
	"\fReportStatus\x12\x11.helper.DataPoint\x1a\x16.google.protobuf.Empty(\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_service_proto_goTypes = []any{
	(*DataPoint)(nil),     // 0: helper.DataPoint
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_service_proto_depIdxs = []int32{
	0, // 0: helper.Collector.ReportStatus:input_type -> helper.DataPoint
	1, // 1: helper.Collector.ReportStatus:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
